# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_auto_20170912_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verified_code',
            field=models.CharField(default='XPTRYQXF', max_length=8),
        ),
    ]
