# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_auto_20170912_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verified_code',
            field=models.CharField(default='VZRBYBVA', max_length=8),
        ),
    ]
